name: Bug report
description: Report something that is broken or incorrect
labels: bug
body:

  - type: textarea
    id: description
    attributes:
      label: Description of the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: command_used
    attributes:
      label: Command used and terminal output
      description: Steps to reproduce the behaviour. Please paste the command you used to launch the pipeline and the output from your terminal.
      render: console
      placeholder: |
        $ run_tobias.bash ...

        Some output where something broke

  - type: textarea
    id: files
    attributes:
      label: Relevant files
      description: |
        Please drag and drop any relevant files here. Create a `.zip` archive if the extension is not allowed.
        Your verbose log file `.nextflow.log` is often useful _(this is a hidden file in the directory where you launched the pipeline)_ as well as custom Nextflow configuration files.
        If the bug is related to a GUI, add screenshots to help explain your problem.

  - type: textarea
    id: system
    attributes:
      label: System information
      description: |
        * Snakemake version _(eg. 7.32.4)_
        * Hardware _(eg. HPC, Desktop)_
        * OS _(eg. Ubuntu Linux, macOS)_
        * Version of CCBR/CCBR_tobias _(eg. 0.2, 0.3)_
