## you probably need to change or comment/uncomment some of these
#
# The working dir... output will be in the results subfolder of the workdir
workdir: "WORKDIR"
#
# samples are entered in the following format:
# data:
#   Group1/Condition1: [list of group1 sample bams]
#   Group2/Condition2: [list of group2 sample bams]
data:
  iCre_D0: [/data/CCBR/projects/ccbr872/atacseq/test/bam/iCre_D0_*.qsorted.bam]
  iCre_D2_EpiLSC: [/data/CCBR/projects/ccbr872/atacseq/test/bam/iCre_D2_EpiLSC_*.qsorted.bam]
  D3_NMP_iCre_Dox: [/data/CCBR/projects/ccbr872/atacseq/test/bam/D3_NMP_iCre_Dox_*.qsorted.bam]
peaks: "/data/CCBR/projects/ccbr872/atacseq/test/peaks/genrich/tn5knicks/query_regions.bed"
genome: "mm10"

# D3_FGF_iCre_Dox
# D3_FGF_Nkx1_2_Dox
# D3_NMP_iCre
# D3_NMP_iCre_Dox
# D3_NMP_iFSp5_Dox
# D3_NMP_Nkx1_2_Dox
# D4_Meso_iCre_Dox
# D4_Meso_Nkx1_2_Dox
# D4_Neural_iCre_Dox
# D4_Neural_Nkx1_2_Dox
# iCre_D0
# iCre_D2_EpiLSC
# Sp5_8_dko_1_D3_NMP
# WT_7_D3_NMP

# May need to change some of these
# resourcesdir: # defaults to PIPELINE_HOME/resources
# scriptsdir:   # defaults to PIPELINE_HOME/scripts
#
# You may never need to change these
tools: "PIPELINE_HOME/config/tools.yaml"
reffa:
  mm10: "/data/CCBR_Pipeliner/db/PipeDB/Indices/mm10_basic/mm10_basic.fa"
  hg38: "/data/CCBR_Pipeliner/db/PipeDB/Indices/hg38_basic/hg38_basic.fa"
autocorrect_extra_params: ""
blacklist: ""