## you probably need to change or comment/uncomment some of these

# The working dir... output will be in the results subfolder of the workdir
workdir: "WORKDIR"
# to use the workdir version of cluster.json comment out the following line
# clusterjson: "PIPELINE_HOME/config/cluster.json"
# define scripts/resource folders ... if you curated your own please add them here
resourcesdir: "PIPELINE_HOME/resources" # defaults to PIPELINE_HOME/resources
# scripts folder is copied over to the workdir from pipeline_home.
# to use the workdir version of scripts comment out the following line
# scriptsdir: "PIPELINE_HOME/scripts"  # defaults to PIPELINE_HOME/scripts
# preinstalled modules on biowulf that will be used
# to use the workdir version of tools.yaml comment out the following line
tools: "PIPELINE_HOME/config/tools.yaml"
# uropa json base template is copied over to the workdir from pipeline_home.
# to use the workdir version of uropa_base_config.yaml comment out the following line
uropabaseyaml: "PIPELINE_HOME/config/uropa_base_config.yaml"

containers:
  tobias: "docker://nciccbr/ccbr_tobias:v2"
  base: "docker://nciccbr/ccbr_ubuntu_base_20.04:v6"

# samples are entered in the following format:
# data:
#   Group1/Condition1: [list of group1 sample bams]
#   Group2/Condition2: [list of group2 sample bams]
# wildcards can be used and pipeline will populate the list with glob

data:
  iCre_D0: [PIPELINE_HOME/.test/rawdata/iCre_D0_*.dedup.bam]
  D4_Meso_iCre_Dox: [PIPELINE_HOME/.test/rawdata/D4_Meso_iCre_Dox_*.dedup.bam]

# contrasts are list of 2 groups/conditions, for eg:
# contrasts:
#   contrastA : ["group2","group1"]

contrasts:
  A: ["D4_Meso_iCre_Dox","iCre_D0"]

# peaks BED file to use
peaks: "PIPELINE_HOME/.test/rawdata/merged.bed"

# genome specific resources
genome: "mm10"
mm10:
  reffa: "/data/CCBR_Pipeliner/db/PipeDB/Indices/mm10_basic/mm10_basic.fa"
  gtf: "/data/CCBR_Pipeliner/db/PipeDB/Indices/GTFs/mm10/gencode.vM21.annotation.gtf"
hg38:
  reffa: "/data/CCBR_Pipeliner/db/PipeDB/Indices/hg38_basic/hg38_basic.fa"
  gtf: "/data/CCBR_Pipeliner/db/PipeDB/Indices/GTFs/hg38/gencode.v30.annotation.gtf"
hg19:
  reffa: "/data/CCBR_Pipeliner/db/PipeDB/Indices/hg19_basic/hg19.copy.fa"
  gtf: "/data/CCBR_Pipeliner/db/PipeDB/Indices/GTFs/hg19/gencode.v19.annotation.gtf"

# blacklist BED file
blacklist: ""

# choose PFMs to use for motif to gene mapping prior to creating the TF binding network
pfm: "PIPELINE_HOME/resources/JASPAR2024_CORE_non-redundant_pfms_jaspar.txt"

# choose the motifs database to use
# motifs: "PIPELINE_HOME/resources/HOCOMOCOv11_HUMAN_core_motifs.txt"
# motifs: "PIPELINE_HOME/resources/HOCOMOCOv11_HUMAN_full_motifs.txt"
# motifs: "PIPELINE_HOME/resources/HOCOMOCOv11_HUMAN_MOUSE_core_motifs.txt"
# motifs: "PIPELINE_HOME/resources/HOCOMOCOv11_HUMAN_MOUSE_full_motifs.txt"
motifs: "PIPELINE_HOME/resources/HOCOMOCOv11_MOUSE_core_motifs.txt"
# motifs: "PIPELINE_HOME/resources/HOCOMOCOv11_MOUSE_full_motifs.txt"
# motifs: "PIPELINE_HOME/resources/JASPAR2020_core_nonredundant_motifs.txt"
# motifs: "PIPELINE_HOME/resources/JASPAR2020_core_redundant_motifs.txt"
# motifs: "PIPELINE_HOME/resources/JASPAR2020_vertebrate_nonredundant_motifs.txt"
# motifs: "PIPELINE_HOME/resources/JASPAR2020_vertebrate_redundant_motifs.txt"

# other parameters
autocorrect_extra_params: ""
footprinting_extra_params: ""
bindetect_extra_params: ""

# favorite motifs to investigate for custom heatmap & aggregate plots
# fav_motifs:
#   - JUND_HUMAN.H11MO.0.A_JUND_HUMAN.H11MO.0.A
#   - JUNB_HUMAN.H11MO.0.A_JUNB_HUMAN.H11MO.0.A
#   - JUN_HUMAN.H11MO.0.A_JUN_HUMAN.H11MO.0.A